name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    env:
      COVERAGE_OUTPUT: coverage
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: --out-dir ${{ env.COVERAGE_OUTPUT }}go test --coverprofile=coverage/coverage.out
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        run: |
          sonnar-scanner --define sonar.go.tests.reportPaths=${{ env.COVERAGE_OUTPUT }}/coverage.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}